import Language from './Language';

const En: Language = {
  spanishLanguage: 'Spanish',
  englishLanguage: 'English',
  sidebarLondon: 'London 💂🏻‍♀️',
  sidebarToronto: 'Toronto 🍁',
  sidebarSingapore: 'Singapore 🏯',
  sidebarTitle: 'Choose a city',
  sidebarForm: "Something's wrong? Leave your contact ",
  sidebarFormLink: 'here',
  formTitle: 'Leave here your contact',
  formName: 'Name',
  formEmail: 'Email',
  formCity: 'City',
  formBirthdate: 'Birthdate',
  formPhoneNumber: 'Phone number',
  formSubmitButton: 'Submit',
  formCloseButton: 'Cancel',
  fullWeatherReportCloseButton: 'Close',
  emptyContentTitle: "Looks like you haven't selected a city yet",
  emptyContentSpan: 'Please, pick a city from the sidebar',
  dataFormat: 'en',
  humiditySpan: 'Humidity',
  pressureSpan: 'Pressure',
  windSpeedSpan: "Wind's speed",
  rainProbSpan: 'Storm probability',
  minTempSpan: 'Min. temperature',
  maxTempSpan: 'Max. temperature',
  serverErrorMessage: 'Server error',
  clientErrorMessage: 'Client error',
  serverErrorTip: 'Please try again later',
  clientErrorTip: 'Please try again later',
};

export default En;
